### ISSUE TITLE
项目编译后占用过大

### ISSUE THREAD

**Issue by Needrom** [eggfly/StickWatch#1]
Arduino 版本:1.8.8
硬件:M5stick with mpu6050
参数选择
<img width="299" alt="2019-02-18 20 09 00" src="https://user-images.githubusercontent.com/12799075/52950474-3fdea400-33ba-11e9-8794-61c8aceef6a0.png">

编译错误:
<img width="1280" alt="2019-02-18 16 07 34" src="https://user-images.githubusercontent.com/12799075/52950513-5dac0900-33ba-11e9-90fc-423d146d4eeb.png">

需要回滚到：d8a3682105554ed53c468111379bb1e573392134 版本才编译通过

**Comment by eggfly** [comment]
不需要回滚，在Arduino里，选工具->Partition Scheme->No OTA，这样一下应该就好了。

![1004817850](https://user-images.githubusercontent.com/922837/53004031-40834300-346b-11e9-8a4d-ce4f178ba453.jpg)

我在项目readme加一个备注吧，谢谢！
