### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by agentariba** [eggfly/StickWatch#4]
When I compile it as said the screen shows nothing. The only difference I made is that I lowered the upload speed115200, because if I try to upload with921600 I get "A fatal error occurred: Timed out waiting for packet header"

**Comment by tstanescu1** [comment]
I also got a black screen - the screen ref # is ST7735, which is a RGB controller. U8g2 however is a monochrome lib, so st7735 can not be supported.

**Comment by eggfly** [comment]
Use StickC to upload Stick code?
